/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import entity.Calculo;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author Cristian Jucoski
 */
public class TelaPrincipal extends javax.swing.JFrame {


    /**
     * Creates new form Teste
     */
    public TelaPrincipal() {
        initComponents();
        getRootPane().setDefaultButton(btnCalcular);
        this.setIconImage(new ImageIcon(getClass().getResource("/View/calculator-icon.png")).getImage());
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtExposição = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtnivelruido = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblTempo_exposisao = new javax.swing.JLabel();
        lblNivelRuido = new javax.swing.JLabel();
        lblMaximoPermitido = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TxtTempoExposição1 = new javax.swing.JTextField();
        TxtTempoExposição2 = new javax.swing.JTextField();
        TxtTempoExposição3 = new javax.swing.JTextField();
        TxtTempoExposição5 = new javax.swing.JTextField();
        TxtTempoExposição4 = new javax.swing.JTextField();
        TxtMaximoPermitido2 = new javax.swing.JTextField();
        TxtMaximoPermitido1 = new javax.swing.JTextField();
        TxtMaximoPermitido3 = new javax.swing.JTextField();
        TxtMaximoPermitido4 = new javax.swing.JTextField();
        TxtMaximoPermitido5 = new javax.swing.JTextField();
        TxtSubTotal5 = new javax.swing.JTextField();
        TxtSubTotal4 = new javax.swing.JTextField();
        TxtSubTotal3 = new javax.swing.JTextField();
        TxtSubTotal2 = new javax.swing.JTextField();
        TxtSubTotal1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtTotalGeral = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnLimpar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora de Insalubridade");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Calculo de Insalurbridade"));

        jLabel1.setText("Tempo de Exposição:");

        jLabel6.setText("Nivel de Ruido (dB):");

        btnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/calculator-icon.png"))); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.setToolTipText("");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        btnCalcular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCalcularKeyPressed(evt);
            }
        });

        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/draw-eraser-icon.png"))); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        jLabel7.setText("Tempo Exposição:");

        jLabel8.setText("Nivel de Ruido:");

        lblTempo_exposisao.setText("- -");

        lblNivelRuido.setText("- -");

        lblMaximoPermitido.setText("- -");

        jLabel12.setText("Tempo Maximo Permitido:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCalcular)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnivelruido, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtExposição, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNivelRuido)
                            .addComponent(lblMaximoPermitido)
                            .addComponent(lblTempo_exposisao))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtExposição, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(lblTempo_exposisao))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblNivelRuido)
                    .addComponent(jLabel6)
                    .addComponent(txtnivelruido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaximoPermitido)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular)
                    .addComponent(btnLimpar))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jLabel10.setText("By: Cristian Jucoski");

        jLabel11.setText("Versão : 1.0");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado Total"));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setText("Tempo de Exposição:");

        jLabel9.setText("Maximo Permitido:");

        TxtTempoExposição1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTempoExposição1ActionPerformed(evt);
            }
        });

        TxtTempoExposição2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTempoExposição2ActionPerformed(evt);
            }
        });

        TxtTempoExposição3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTempoExposição3ActionPerformed(evt);
            }
        });

        TxtTempoExposição5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTempoExposição5ActionPerformed(evt);
            }
        });

        TxtTempoExposição4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTempoExposição4ActionPerformed(evt);
            }
        });

        TxtMaximoPermitido2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtMaximoPermitido2ActionPerformed(evt);
            }
        });

        TxtMaximoPermitido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtMaximoPermitido1ActionPerformed(evt);
            }
        });

        TxtMaximoPermitido3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtMaximoPermitido3ActionPerformed(evt);
            }
        });

        TxtMaximoPermitido4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtMaximoPermitido4ActionPerformed(evt);
            }
        });

        TxtMaximoPermitido5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtMaximoPermitido5ActionPerformed(evt);
            }
        });

        TxtSubTotal5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSubTotal5ActionPerformed(evt);
            }
        });

        TxtSubTotal4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSubTotal4ActionPerformed(evt);
            }
        });

        TxtSubTotal3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSubTotal3ActionPerformed(evt);
            }
        });

        TxtSubTotal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSubTotal2ActionPerformed(evt);
            }
        });

        TxtSubTotal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSubTotal1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Sub Total:");

        TxtTotalGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTotalGeralActionPerformed(evt);
            }
        });

        jLabel4.setText("Total Geral:");

        btnLimpar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/draw-eraser-icon.png"))); // NOI18N
        btnLimpar1.setText("Limpar");
        btnLimpar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLimpar1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtTotalGeral)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(TxtTempoExposição1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtTempoExposição2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(TxtMaximoPermitido1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TxtMaximoPermitido2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(TxtSubTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtSubTotal2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(TxtTempoExposição3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtTempoExposição4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtTempoExposição5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(TxtMaximoPermitido3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtMaximoPermitido4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(TxtSubTotal3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtSubTotal4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtMaximoPermitido5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtSubTotal5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtTempoExposição1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtTempoExposição2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtTempoExposição3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtTempoExposição5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtTempoExposição4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(TxtMaximoPermitido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TxtMaximoPermitido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TxtMaximoPermitido3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TxtMaximoPermitido4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TxtMaximoPermitido5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtSubTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtSubTotal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtSubTotal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtSubTotal4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtSubTotal5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtTotalGeral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(btnLimpar1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(0, 451, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed

        limpar();
        txtExposição.requestFocus();
    }//GEN-LAST:event_btnLimparActionPerformed
                     
    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
       Calculo C = new Calculo();
        if (txtExposição.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Favor inserir um valor no Campo Exposição!");
        }if (txtnivelruido.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Favor inserir um valor no Campo Nivel de ruido!");
        }else{
       C.setTempo_uso(Integer.parseInt(txtExposição.getText()));
       C.setNivel_ruido(Integer.parseInt(txtnivelruido.getText()));
       C.calculo_tempoMaximo();
       lblNivelRuido.setText(C.getNivel_ruido()+" dB");
       lblMaximoPermitido.setText(C.getTempo_maximo()+" Min");
       lblTempo_exposisao.setText(C.getTempo_uso()+" Min");
       lblNivelRuido.setForeground(Color.red);
       lblMaximoPermitido.setForeground(Color.red);
       lblTempo_exposisao.setForeground(Color.red);
        }
        if (TxtTempoExposição1.getText().equals("")){
            TxtTempoExposição1.setText(C.getTempo_uso()+"");
            TxtMaximoPermitido1.setText(C.getTempo_maximo()+"");
            
        } else {
            if (TxtTempoExposição2.getText().equals("")){
            TxtTempoExposição2.setText(C.getTempo_uso()+"");
            TxtMaximoPermitido2.setText(C.getTempo_maximo()+"");
            
        }else{ 
                if (TxtTempoExposição3.getText().equals("")){
            TxtTempoExposição3.setText(C.getTempo_uso()+"");
            TxtMaximoPermitido3.setText(C.getTempo_maximo()+"");
            
        }else{
                if (TxtTempoExposição4.getText().equals("")){
            TxtTempoExposição4.setText(C.getTempo_uso()+"");
            TxtMaximoPermitido4.setText(C.getTempo_maximo()+"");
            
        }else{
                    if (TxtTempoExposição5.getText().equals("")){
            TxtTempoExposição5.setText(C.getTempo_uso()+"");
            TxtMaximoPermitido5.setText(C.getTempo_maximo()+"");
            
        }
        }
        }        
        }    
        }

                
    }//GEN-LAST:event_btnCalcularActionPerformed
        
    private void btnCalcularKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCalcularKeyPressed
      
    }//GEN-LAST:event_btnCalcularKeyPressed

    private void TxtTempoExposição1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTempoExposição1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTempoExposição1ActionPerformed

    private void TxtTempoExposição2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTempoExposição2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTempoExposição2ActionPerformed

    private void TxtTempoExposição3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTempoExposição3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTempoExposição3ActionPerformed

    private void TxtTempoExposição5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTempoExposição5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTempoExposição5ActionPerformed

    private void TxtTempoExposição4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTempoExposição4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTempoExposição4ActionPerformed

    private void TxtMaximoPermitido2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtMaximoPermitido2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtMaximoPermitido2ActionPerformed

    private void TxtMaximoPermitido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtMaximoPermitido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtMaximoPermitido1ActionPerformed

    private void TxtMaximoPermitido3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtMaximoPermitido3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtMaximoPermitido3ActionPerformed

    private void TxtMaximoPermitido4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtMaximoPermitido4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtMaximoPermitido4ActionPerformed

    private void TxtMaximoPermitido5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtMaximoPermitido5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtMaximoPermitido5ActionPerformed

    private void TxtSubTotal5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSubTotal5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSubTotal5ActionPerformed

    private void TxtSubTotal4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSubTotal4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSubTotal4ActionPerformed

    private void TxtSubTotal3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSubTotal3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSubTotal3ActionPerformed

    private void TxtSubTotal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSubTotal2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSubTotal2ActionPerformed

    private void TxtSubTotal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSubTotal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSubTotal1ActionPerformed

    private void btnLimpar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpar1ActionPerformed

    private void TxtTotalGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTotalGeralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTotalGeralActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtMaximoPermitido1;
    private javax.swing.JTextField TxtMaximoPermitido2;
    private javax.swing.JTextField TxtMaximoPermitido3;
    private javax.swing.JTextField TxtMaximoPermitido4;
    private javax.swing.JTextField TxtMaximoPermitido5;
    private javax.swing.JTextField TxtSubTotal1;
    private javax.swing.JTextField TxtSubTotal2;
    private javax.swing.JTextField TxtSubTotal3;
    private javax.swing.JTextField TxtSubTotal4;
    private javax.swing.JTextField TxtSubTotal5;
    private javax.swing.JTextField TxtTempoExposição1;
    private javax.swing.JTextField TxtTempoExposição2;
    private javax.swing.JTextField TxtTempoExposição3;
    private javax.swing.JTextField TxtTempoExposição4;
    private javax.swing.JTextField TxtTempoExposição5;
    private javax.swing.JTextField TxtTotalGeral;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnLimpar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblMaximoPermitido;
    private javax.swing.JLabel lblNivelRuido;
    private javax.swing.JLabel lblTempo_exposisao;
    private javax.swing.JTextField txtExposição;
    private javax.swing.JTextField txtnivelruido;
    // End of variables declaration//GEN-END:variables

public void limpar(){
txtExposição.setText("");
txtnivelruido.setText("");
lblMaximoPermitido.setText("- -");
lblNivelRuido.setText("- -");
lblTempo_exposisao.setText("- -");
lblMaximoPermitido.setForeground(Color.black);
lblNivelRuido.setForeground(Color.black);
lblTempo_exposisao.setForeground(Color.black);
}
}
